export * from './404';
export * from './login';
export * from './register';
export * from './home';
export * from './logout';
export * from './form/contact';
export * from './unauthorized';
export * from './admin/home';
export * from './admin/user';